export const actionType = {
  FETCHING_START: 'FETCHING_START',
  FETCHING_SUCCESS: 'FETCHING_SUCCESS',
  FETCHING_ERROR: 'FETCHING_ERROR',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  FETCHING_SEARCHED_PRODUCTS: 'FETCHING_SEARCHED_PRODUCTS',
  FETCHING_CATEGORY_PRODUCTS: 'FETCHING_CATEGORY_PRODUCTS',
  FETCHING_DISPLAY_PRODUCTS: 'FETCHING_DISPLAY_PRODUCTS',
};
